### ISSUE TITLE
Having trouble importing pylsl

### ISSUE THREAD

**Issue by devaka40** [chkothe/pylsl#6]
Hi everyone, I having trouble importing pylsl. Everytime I try to import it I get:

Traceback (most recent call last):
  File "C:/Users/computer/PycharmProjects/pythonProject1/MuseRead.py", line 33, in <module>
    import pylsl
  File "C:\Users\computer\PycharmProjects\pythonProject1\venv\lib\site-packages\pylsl\__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "C:\Users\computer\PycharmProjects\pythonProject1\venv\lib\site-packages\pylsl\pylsl.py", line 1217, in <module>
    lib = CDLL(libpath)
  File "C:\Users\computer\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

I'm tried looking at the installation guide for pylsl and the only thing I can see is to use pip install pylsl which is what I used. 

Thanks in advance to everyone that helps.

**Comment by rakeshbci** [comment]
I am getting the same error.

**Comment by rakeshbci** [comment]
Traceback (most recent call last):
  File "time1.py", line 1, in <module>
    from pylsl import StreamInlet, resolve_stream
  File "C:\Users\rakes\AppData\Local\Programs\Python\Python38\lib\site-packages\pylsl\__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "C:\Users\rakes\AppData\Local\Programs\Python\Python38\lib\site-packages\pylsl\pylsl.py", line 1217, in <module>
    lib = CDLL(libpath)
  File "C:\Users\rakes\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by bboylalu** [comment]
Same goes here:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1\anaconda3\lib\site-packages\pylsl\__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "C:\Users\user1\anaconda3\lib\site-packages\pylsl\pylsl.py", line 1217, in <module>
    lib = CDLL(libpath)
  File "C:\Users\user1\anaconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Rakesh420** [comment]
@bboyalu I got my problem solved, I had a rogue DLL in my system. Add a print(libpath) immediately before the lib = CDLL(libpath) line and try to import pylsl again? The location should match with the python library location where pylsl is present.

**Comment by bboylalu** [comment]
@Rakesh420 Ah, yes, thank you so much! For some reason it was pointing to the Muse SDK installation folder, C:\Program Files (x86)\Muse\lsl.dll. I uninstalled the Muse SDK and now I can import pylsl without any issue.

I think this is the piece of code that does that, but Muse SDK's lsl.dll is not working in this situation.
`path = util.find_library('lsl' + bitness + debugsuffix) or \
                   util.find_library('liblsl' + bitness + debugsuffix)`

**Comment by rakeshbci** [comment]
@bboylalu I had the same issue with the Muse SDK. I deleted the lsl.dll in the Muse folder. And when the printed the libpath, it showed in the proper directory. Now pylsl is working in my computer.

**Comment by cboulay** [comment]
This repo should be archived. Please use https://github.com/labstreaminglayer/liblsl-Python
